/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script.
 *
 * These definitions bend every interrupt handler that is defined CMSIS style
 * to the weak symbol exported by libopencm3.
 */

#define TIMER_0_IRQHandler timer_0_isr
#define TIMER_1_IRQHandler timer_1_isr
#define TIMER_2_IRQHandler timer_2_isr
#define TIMER_3_IRQHandler timer_3_isr
#define PWM_WRAP_IRQHandler pwm_wrap_isr
#define USBCTRL_IRQHandler usbctrl_isr
#define XIP_IRQHandler xip_isr
#define PIO0_0_IRQHandler pio0_0_isr
#define PIO0_1_IRQHandler pio0_1_isr
#define PIO1_0_IRQHandler pio1_0_isr
#define PIO1_1_IRQHandler pio1_1_isr
#define DMA_0_IRQHandler dma_0_isr
#define DMA_1_IRQHandler dma_1_isr
#define IO_BANK0_IRQHandler io_bank0_isr
#define IO_QSPI_IRQHandler io_qspi_isr
#define SIO_PROC0_IRQHandler sio_proc0_isr
#define SIO_PROC1_IRQHandler sio_proc1_isr
#define CLOCKS_IRQHandler clocks_isr
#define SPI0_IRQHandler spi0_isr
#define SPI1_IRQHandler spi1_isr
#define UART0_IRQHandler uart0_isr
#define UART1_IRQHandler uart1_isr
#define ADC_FIFO_IRQHandler adc_fifo_isr
#define I2C0_IRQHandler i2c0_isr
#define I2C1_IRQHandler i2c1_isr
#define RTC_IRQHandler rtc_isr
